# Generated by Django 4.1.7 on 2023-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationName', models.CharField(max_length=50)),
                ('destinationDescription', models.TextField(max_length=300)),
                ('destinationPrice', models.IntegerField()),
                ('destinationImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
